### ISSUE TITLE
Discussion on how to send data coming from any simulation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#67]
GAMA will be taken as an example but it has only to be seen as one simulation tool that wants to expose a result to cityIO

So here is the current workflow.

1. (Optional) Run this model from GAMA (version greater that 1.8 RC2)
2. Once the model runs it will push a geojson to cityIO
this geojson is this one https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/GAMA/cityIO_Gama/results/people.geojson
3. Once it's pull in cityIO this is what I have (see https://cityio.media.mit.edu/api/table/cityIO_Gama_Simulation)

`````
{"meta":{"id":"28cbba0dbefa9dc81ea5c8027473bea378037f199c9281e5f349ce2a696225d8","timestamp":1553106642702,"apiv":"2.1.0"},"header":{"name":"","spatial":{"nrows":0,"ncols":0,"physical_longitude":0,"physical_latitude":0,"longitude":0,"latitude":0,"cellSize":0,"rotation":0},"owner":{"name":"","title":"","institute":""},"block":null,"mapping":null},"grid":null,"objects":null}
`````

Now the question is should an external simulation tool should push to cityIO or should we have a dedicated server (e.g gama.media.mit.edu) but then it involves more maintenance, who is taking care of gama.media.mit.edu? the same as the one taking care of cityio.media.mit.edu?

**Comment by RELNO** [comment]
Adding @doorleyr to the mix -- https://github.com/CityScope/CS_choiceModels/blob/master/python/mobilityApi.py might be an example of how it's done in Mocho

**Comment by yasushisakai** [comment]
I will look into the data to see whats happening.

for 
> the question is should an external simulation tool should push to cityIO or should we have a
> dedicated server.

![](http://networkcultures.org/unlikeus/wp-content/uploads/sites/2/2013/03/networktypes.png)

**open for discussion.** @agrignard whats your thought? It will be a design decision, my opinon is to have cityio concentrating to be the librarian for table states... not for simulation results. (especially if there is a constant stream of results.)

Logistic wise, there are two things to maintain,
the machine and the program. The current responsibilities for the cityio machine is

cityio machine ->  @yasushisakai
cityio -> @yasushisakai
choiceModels ->  @doorleyr

the machine maintainer makes sure both ```cityio``` and ```choiceModels``` are running, more like a sys admin. If there is an error booting the program, the machine maintainer reports to the program maintainer.

gama.media.mit.edu, implies there will be a dedicated maintainer for the machine and the program. which is fine. The HCU side might decide on having an external computer, we never know. Andorra, Helsinki, I don’t know.

Alternatively, the server maintainer can open a specific port for the GAMA and give an entry endpoint like ```https://cityio.media.mit.edu/gama/``` the process handling the gama computation, will take responsibility from there, providing endpoints like ```https://cityio.media.mit.edu/gama/sim/``` This is the current choiceModels approach. Which I think is better in terms of network latency and so forth, since processes can talk locally, resulting the MIT city science-brewed processes lives under one roof.

**Comment by RELNO** [comment]
> Alternatively, the server maintainer can open a specific port for the GAMA and give an entry endpoint like https://cityio.media.mit.edu/gama/ the process handling the gama computation, will take responsibility from there

Regarding only to this last part - I assume it's a more concise, microservice like approach to look at cityIO as sort of an overarching theme for all CityScope external services. So a `https://cityio.media.mit.edu/happiness_simulation` is clearly a subset of the `cityIO` world, whereis `happinessSimulation.media.mit.edu` is just a spinoff waiting for a VC.

**Comment by yasushisakai** [comment]
I think it is worth elevating this topic for the first cityio conference, sometime next week

**Comment by yasushisakai** [comment]
@agrignard I checked the json data that was fed, when it checks(*1) the data if it’s our json format, it is parsed as an instance of a Table class object. In other words, anything out side of https://github.com/CityScope/CS_CityIO_Backend/blob/master/models/models.go is dropped.

I think this wasn’t clearly stated nor disscussed in the documentation, where it can take any json, right now it tries to fit into the perferred format.

I change it so that input json data is left untouched, but until that, you can add anything to the `objects` key.

*1 checks for types, and whether anything is missing from the class declaration.

**Comment by agrignard** [comment]
Thanks. We could put the information in Object however if we do that we kill all the compatibility with any GeoJson file, so I would be more in favor to be able to send a pure GeoJson. 

Regarding the stability of the server I don't know if everything should be handle only by cityIO or if a simulation should send his data to another server (in that case which one? ). I think that something that really need to be discussed if we want to have the possibility to connect cityIO to third part software

**Comment by agrignard** [comment]
fixed in 
https://github.com/CityScope/CS_CityIO_Backend/commit/17983027c1aeafcadfa71ef25c962bb71f226853

As discussed recently for now on (as a "temporary" solution) the information is sent in the "objects" field so that it is compatible with cityIO convention.

A genric example can be now found in here
https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples/GAMA/cityIO_Gama
